server:
  port: 8080

spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: dhc
    password: 11111111

  session:
    store-type: none

dhc-security-core:
  welcome-page: /index.html
  browser:
    login-page: /module/login/default-login.html
    login-process-url: /api/login
    logout-process-url:
  app:
    login-page:
    login-process-url:
    logout-process-url:

